 /******************************************************************************
 *
 * Autosar name : Port Driver
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for TM4C123GH6PM Microcontroller - Port Driver
 *
 * Author: Esmail Ahmed
 ******************************************************************************/

#include "Port.h"

/*
 * AUTOSAR Version 4.3.1
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (3U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (1U)

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of Port_PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of Port_PBcfg.c does not match the expected version"
#endif

/* 
 * Note:
 *      The name of each pin is specified at first, then the following features
 *      are configured in the following order:
 *        1. Pin number
 *        2. Port number
 *        3. Pin direction
 *        4. Internal pull-up/down resistor control 
 *        5. Pin mode
 *        6. Pin initial value               
 *        7. Pin direction changeable
 *        8. Pin mode changeable
 *
 */
const Port_ConfigType Port_Configuration =
{
 /* PORT_A_PIN_0 */
  PIN_0,
  PORT_A,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL, 
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_A_PIN_1 */
  PIN_1,
  PORT_A,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_A_PIN_2 */
  PIN_2,
  PORT_A,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_A_PIN_3 */
  PIN_3,
  PORT_A,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_A_PIN_4 */
  PIN_4,
  PORT_A,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_A_PIN_5 */
  PIN_5,
  PORT_A,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_A_PIN_6 */
  PIN_6,
  PORT_A,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_A_PIN_7 */
  PIN_7,
  PORT_A,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_B_PIN_0 */
  PIN_0,
  PORT_B,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_B_PIN_1 */
  PIN_1,
  PORT_B,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_B_PIN_2 */
  PIN_2,
  PORT_B,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_B_PIN_3 */
  PIN_3,
  PORT_B,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_B_PIN_4 */
  PIN_4,
  PORT_B,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_B_PIN_5 */
  PIN_5,
  PORT_B,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_B_PIN_6 */
  PIN_6,
  PORT_B,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_B_PIN_7 */
  PIN_7,
  PORT_B,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_C_PIN_0 */
  PIN_0,
  PORT_C,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_C_PIN_1 */
  PIN_1,
  PORT_C,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_C_PIN_2 */
  PIN_2,
  PORT_C,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_C_PIN_3 */
  PIN_3,
  PORT_C,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_C_PIN_4 */
  PIN_4,
  PORT_C,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_C_PIN_5 */
  PIN_5,
  PORT_C,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_C_PIN_6 */
  PIN_6,
  PORT_C,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_C_PIN_7 */
  PIN_7,
  PORT_C,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
 
 /* PORT_D_PIN_0 */
  PIN_0,
  PORT_D,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_D_PIN_1 */
  PIN_1,
  PORT_D,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_D_PIN_2 */
  PIN_2,
  PORT_D,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_D_PIN_3 */
  PIN_3,
  PORT_D,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_D_PIN_4 */
  PIN_4,
  PORT_D,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_D_PIN_5 */
  PIN_5,
  PORT_D,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_D_PIN_6 */
  PIN_6,
  PORT_D,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_D_PIN_7 */
  PIN_7,
  PORT_D,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_E_PIN_0 */
  PIN_0,
  PORT_E,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_E_PIN_1 */
  PIN_1,
  PORT_E,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_E_PIN_2 */
  PIN_2,
  PORT_E,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_E_PIN_3 */
  PIN_3,
  PORT_E,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
  /* PORT_E_PIN_4 */
  PIN_4,
  PORT_E,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_E_PIN_5 */
  PIN_5,
  PORT_E,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_F_PIN_0 */
  PIN_0,
  PORT_F,
  PORT_PIN_IN,  
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_F_PIN_1 */
  PIN_1,
  PORT_F,
  PORT_PIN_OUT,  
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_NOT_CHANGEABLE,
  PORT_PIN_NOT_CHANGEABLE,
  
 /* PORT_F_PIN_2 */
  PIN_2,
  PORT_F,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_F_PIN_3 */
  PIN_3,
  PORT_F,
  PORT_PIN_IN,
  PORT_PIN_NO_PULL,
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_CHANGEABLE,
  PORT_PIN_CHANGEABLE,
  
 /* PORT_F_PIN_4 */
  PIN_4,
  PORT_F,
  PORT_PIN_IN,
  PORT_PIN_PULL_UP, 
  PORT_DIGITAL_IO,
  PORT_INITIAL_VALUE_OFF,
  PORT_PIN_NOT_CHANGEABLE,
  PORT_PIN_NOT_CHANGEABLE
};



